excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://alumni.thunderbirdband.ca
title: TMBAA
tagline: Thunderbird Marching Band Alumni Association
description: We are the Thunderbird Marching Band Alumni Association. Our mission is to support the students of the Thunderbird Marching Band at UBC.
paginate: 5
